source 'https://rubygems.org'

# Older json_pure required to work with Ruby 1.9
gem 'json_pure', '~> 1.8'
gem 'puppet', '~> 4.2'

group :test do
  gem 'rspec', '~> 3.1'
end

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
