#!/usr/bin/env ruby
require 'json'
require File.join(File.expand_path(File.dirname(__FILE__)), 'puppet_module/puppet.rb')

def action_metadata
  metadata = {
    :description => "Cthun Puppet module",
    :actions => [
      { :name => "status",
        :description => "Determine the status of the Puppet agent",
        :input => {
          :type => "object",
        },
        :output => {
          :type => "object"
        }
      },
      { :name => "run",
        :description => "Start a Puppet run",
        :input => {
          :type => "object"
        },
        :output => {
          :type => "object"
        },
        :behaviour => "delayed"
      }
    ]
  }

  puts metadata.to_json
end

def action_status
  puppet_mgr = PuppetManager.new
  puts(puppet_mgr.status.to_json)
end

def action_run
  puppet_mgr = PuppetManager.new
  puts(puppet_mgr.run.to_json)
end

action = ARGV.shift || 'metadata'

Object.send("action_#{action}".to_sym)
