# Specifies a gem mirror; duplicated in acceptance setup
# to ensure a similar environment on acceptance hosts.
source ENV['GEM_SOURCE'] || 'http://rubygems.delivery.puppetlabs.net'

gem 'rake'
gem 'beaker'
