namespace :ci do

  namespace :test do

    task :aio do
      # Start ssh-agent, parse the env variables from its output and add them to ENV
      # The usual `eval $(ssh-agent)` does not work because
      # the exported values will not persist after the statement completes
      # TODO (JS) - QA-2108 - This no longer works for local execution and must be skipped.
      if not ENV['LOCAL_EXECUTION']
        `ssh-agent -t 24h -s`
          .split.map{|e| e.tr(';', '')}
          .map{|e| e.split('=') }
          .select{|e| e.length == 2 && e[0] =~ /[A-Z]+$/ }
          .each {|e| ENV[e[0]] = e[1] }
        `ssh-add "${HOME}/.ssh/id_rsa"`
      end

      if not ENV['TEST_TARGET']
        fail "TEST_TARGET environment variable must be set to the name of a host config e.g. redhat-7-x86_64"
      end
      beaker_cmd = "beaker -h config/nodes/#{ENV['TEST_TARGET']}.yaml "\
         "--tests tests "\
         "--options config/aio/options.rb"
      if ENV['PRESERVE_HOSTS']
        valid_preserve_host_values = ['never', 'always', 'onfail']
        if not valid_preserve_host_values.include?(ENV['PRESERVE_HOSTS'])
          fail "env variable PRESERVE_HOSTS is not set to a valid value of one on #{valid_preserve_host_values.to_s}"
        end
        beaker_cmd = "#{beaker_cmd} --preserve-hosts #{ENV['PRESERVE_HOSTS']}"
      end
      sh(beaker_cmd)
    end
  end

end
