namespace :ci do

  namespace :test do

    task :aio do
      if (ENV['SHA']) && (not ENV['SUITE_COMMIT'])
        ENV['SUITE_COMMIT'] = ENV['SHA']
      end
      unless ENV['SUITE_COMMIT'] then
        fail('SUITE_COMMIT or SHA environment variable must be set to the SHA of the puppet-agent package to test')
      end

      if not ENV['TEST_TARGET']
        fail "TEST_TARGET environment variable must be set to the name of a host config e.g. redhat-7-x86_64"
      end
      beaker_cmd = "beaker -h config/nodes/#{ENV['TEST_TARGET']}.yaml "\
         "--tests tests "\
         "--options config/aio/options.rb"
      if ENV['PRESERVE_HOSTS']
        valid_preserve_host_values = ['never', 'always', 'onfail']
        if not valid_preserve_host_values.include?(ENV['PRESERVE_HOSTS'])
          fail "env variable PRESERVE_HOSTS is not set to a valid value of one on #{valid_preserve_host_values.to_s}"
        end
        beaker_cmd = "#{beaker_cmd} --preserve-hosts #{ENV['PRESERVE_HOSTS']}"
      end
      sh(beaker_cmd)
    end
  end

end
