---
HOSTS:
  master:
    roles:
    - master
    platform: el-7-x86_64
    hypervisor: vcloud
    template: redhat-7-x86_64
  agent-2012-x86_64-rubyx86:
    roles:
    - agent
    platform: windows-2012-64
    ruby_arch: x86
    hypervisor: vcloud
    template: win-2012-x86_64
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
