#!/usr/bin/env ruby
require 'json'

def action_metadata
   metadata = {
    :description => "broken reverse schema 01",
    :wrong_key_here_expected_actions => [         #  <--  error here
      { :name => "string",
        :description => "reverses a string",
        :input => {
          :type => "string",
        },
        :results => {
          :type => "string",
        },
      },
    ],
  }

  puts metadata.to_json
end

def action_string
  string = $stdin.read.chomp
  puts string.reverse.to_json
end

action = ARGV.shift || 'metadata'

Object.send("action_#{action}".to_sym)
