#!/usr/bin/env ruby
require 'json'

def action_metadata
  print 'foo'
end

def action_string
  string = $stdin.read.chomp
  puts string.reverse.to_json
end

action = ARGV.shift || 'metadata'

Object.send("action_#{action}".to_sym)
