#ifndef TEMPLATES_PXP_AGENT_ROOT_PATH_HPP_
#define TEMPLATES_PXP_AGENT_ROOT_PATH_HPP_

#define PXP_AGENT_ROOT_PATH "@ROOT_PATH@"
#define PXP_AGENT_BIN_PATH "@EXECUTABLE_OUTPUT_PATH@"

#endif  // TEMPLATES_PXP_AGENT_ROOT_PATH_HPP_
