#!/usr/bin/env ruby
require 'json'
require_relative './check_output'

def action_metadata
  metadata = {
    :description => "currency conversions",
    :configuration => {
      :type => "object",
      :properties => {
        :rate => {
          :type => "number"
        },
        :fee_percent => {
          :type => "number"
        },
        :fee_max => {
          :type => "number"
        }
      },
      :required => [:rate],
      :additionalProperties => false
    },
    :actions => [
      {
        :name => "convert",
        :description => "converts a foreign currency using given rate and applying a fee",
        :input => {
          :type => "object",
          :properties => {
            :amount => {
              :type => "number"
            },
          },
          :required => [ :amount ]
        },
        :results => {
          :type => "object",
          :properties => {
            :amount => {
              :type => "number"
            },
          },
          :required => [ :amount ]
        }
      },
      {
        :name => "convert2",
        :description => "converts a foreign currency using given rate and applying a fee",
        :input => {
          :type => "object",
          :properties => {
            :amount => {
              :type => "number"
            },
          },
          :required => [ :amount ]
        },
        :results => {
          :type => "object",
          :properties => {
            :amount => {
              :type => "number"
            },
          },
          :required => [ :amount ]
        }
      }
    ]
  }

  puts metadata.to_json
end

def do_convert
  args = JSON.load($stdin)
  check_output_files(args)
  config = args['configuration']
  input = args['input']

  amount = input['amount'] * config['rate']
  fee_percent = config['fee_percent']
  fee = fee_percent.nil? ? 0 : amount * fee_percent / 100
  fee_max = config['fee_max']
  if !fee_max.nil? && fee > fee_max
    fee = fee_max
  end

  amount - fee
end

def action_convert
  results = { :amount => do_convert }
  puts results.to_json
end

def action_convert2
  results = { :amount2 => do_convert } # intentionally doesn't match schema
  puts results.to_json
end

action = ARGV.shift || 'metadata'

Object.send("action_#{action}".to_sym)
