#!/usr/bin/env ruby
require 'json'
require_relative './check_output'

def action_metadata
   metadata = {
    :description => "schema test",
    :configuration => {
      :type => "object",
      :properties => {
        :spam_dir => {
          :type => "string"
        },
        :eggs_dir => {
          :type => "string"
        },
        :beans_file => {
          :type => "string"
        }
      },
      :required => [:spam_dir, :eggs_dir, :beans_file],
      :additionalProperties => false,
    },
    :actions => [
      { :name => "string",
        :description => "reverses a string",
        :input => {
          :type => "object",
          :properties => {
            :argument => {
              :type => "string",
            },
          },
          :required => [ :argument ],
        },
        :results => {
          :type => "object",
          :properties => {
            :output => {
              :type => "string",
            },
          },
          :required => [ :output ],
        },
      },
      { :name => "hash",
        :description => "reverses an element of a hash",
        :input => {
          :type => "object",
          :properties => {
            :the_input => {
              :type => 'string',
            },
          },
          :required => [ :input ],
        },
        :results => {
          :type => "object",
          :properties => {
            :the_input => {
              :type => 'string',
            },
            :the_output => {
              :type => 'string',
            },
          },
          :required => [ :input, :output ],
        },
      },
    ],
  }

  puts metadata.to_json
end

def action_string
  args = JSON.load($stdin)
  check_output_files(args)
  input_args = args['input']
  results = { :output => input_args['argument'].reverse }
  puts results.to_json
end

def action_hash
  args = JSON.load($stdin)
  check_output_files(args)
  input_args = args['input']
  input_args['the_output'] = input_args['the_input'].reverse
  puts input_args.to_json
end

action = ARGV.shift || 'metadata'

Object.send("action_#{action}".to_sym)
