#!/usr/bin/env ruby
require 'json'

def action_metadata
   metadata = {
    :description => "valid schema for unit tests",
    :actions => [
      { :name => "string",
        :description => "reverses a string",
        :input => {
          :type => "object",
          :properties => {
            :argument => {
              :type => "string",
            },
          },
          :required => [ :argument ],
        },
        :output => {
          :type => "object",
          :properties => {
            :output => {
              :type => "string",
            },
          },
          :required => [ :output ],
        },
      },
    ],
  }

  puts metadata.to_json
end

def action_string
  params = JSON.load($stdin)
  output = { :output => params['argument'].reverse }
  puts output.to_json
end

action = ARGV.shift || 'metadata'

Object.send("action_#{action}".to_sym)
