#!/usr/bin/env ruby
require 'json'

def action_metadata
   metadata = {
    :description => "valid schema for unit tests",
    :actions => [
      { :name => "string",
        :description => "reverses a string",
        :input => {
          :type => "string",
        },
        # adding a valid meaningless behaviour just for testing
        :behaviour => "delayed",
        :output => {
          :type => "string",
        },
      },
      { :name => "hash",
        :description => "reverses an element of a hash",
        :input => {
          :type => "object",
          :properties => {
            :input => {
              :type => 'string',
            },
          },
          :required => [ :input ],
        },
        :output => {
          :type => "object",
          :properties => {
            :input => {
              :type => 'string',
            },
            :output => {
              :type => 'string',
            },
          },
          :required => [ :input, :output ],
        },
      },
    ],
  }

  puts metadata.to_json
end

def action_string
  string = JSON.load($stdin)
  puts string.reverse.to_json
end

def action_hash
  hash = JSON.load($stdin)
  hash['output'] = hash['input'].reverse
  puts hash.to_json
end

action = ARGV.shift || 'metadata'

Object.send("action_#{action}".to_sym)
