---
name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Run Script
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: |
          Remove-Item -Path C:\ProgramData\chocolatey\ -Recurse -Force
          $env:chocolateyVersion = '1.4.0'
          [System.Net.ServicePointManager]::SecurityProtocol = 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          $env:PATH += "%ALLUSERSPROFILE%\chocolatey\bin"
          choco install -y mingw-w64 -Version 5.2.0 -source https://www.myget.org/F/puppetlabs
          choco install -y cmake -Version 3.2.2 -source https://www.myget.org/F/puppetlabs
          # choco install -y gettext -Version 0.19.6 -source https://www.myget.org/F/puppetlabs
          # choco install -y pl-toolchain-x64 -Version 2015.12.01.1 -source https://www.myget.org/F/puppetlabs
          # choco install -y pl-boost-x64 -Version 1.58.0.2 -source https://www.myget.org/F/puppetlabs
          # choco install -y pl-openssl-x64 -Version 1.0.24.1 -source https://www.myget.org/F/puppetlabs
          # choco install -y pl-curl-x64 -Version 7.46.0.1 -source https://www.myget.org/F/puppetlabs
          # choco install -y pl-zlib-x64 -Version 1.2.8.1 -source https://www.myget.org/F/puppetlabs
          choco install -y pester -Version 4.10.1
        shell: pwsh
